theme_advanced_toolbar_location: top
theme_advanced_toolbar_align: left
theme_advanced_statusbar_location: bottom
theme_advanced_buttons2_add_before:
  - cut
  - copy
  - paste
  - pastetext
  - pasteword
  - separator
theme_advanced_buttons2_add:
  - forecolor
  - backcolor
theme_advanced_buttons3_add:
  - tablecontrols
  - fullscreen
plugins:
  - table
  - fullscreen
  - contextmenu